### ISSUE TITLE
Can't find a usable init.tcl

### ISSUE THREAD

**Issue by ereday** [JuliaGraphics/Tk.jl#129]
When  I try to import ImageView on julia repl, I got following error: 

import ImageView

> ERROR: LoadError: LoadError: LoadError: Tk.TclError("error initializing Tcl: Can't find a usable init.tcl in the following directories: \n    /opt/anaconda1anaconda2anaconda3/lib/tcl8.5 /mnt/ai/opt/julia/0.5.0/lib/tcl8.5 /mnt/ai/opt/julia/lib/tcl8.5 /mnt/ai/opt/julia/0.5.0/library /mnt/ai/opt/julia/library /mnt/ai/opt/julia/tcl8.5.18/library /mnt/ai/opt/tcl8.5.18/library\n\n\n\nThis probably means that Tcl wasn't installed properly.\n")

However, when I check my paths, I see that, there is a init.tcl file in a path which is included in my `LD_LIBRARY_PATH` variable. So I cannot understand why Tk does cannot  find it.
If it is important init.tcl is under `~/opt/anaconda/lib/tcl8.5/init.tcl `path and this path is included in `LD_LIBRARY_PATH` as I said before.

**Comment by aviks** [comment]
Should be fixed by #148
