### ISSUE TITLE
forward the TkWidget on OS X

### ISSUE THREAD

**Issue by ezaron** [JuliaGraphics/Tk.jl#132]
Hi,
I'll try to be succinct:

The issue:
When running julia on OS X, the Tk widget only appears on the console attached to the computer. Instead, I would like to be able to open and use the Tk widget via remote shell, e.g., "ssh -Y host", which would allow me to work on the host computer, but display the widget back on my remote computer. My specific application is simply to use the Winston package to do some simple graphics for debugging.

Here is what I have found:
I used the MacPorts system to install the X11 variant of the Tk port. I have built some other software which uses the MacPorts libTk (under /opt/local/lib) and it successfully displays windows back on the client computer. [Conversely, the OS X system version of libTk does not do this.]
I noticed under .julia/ there is a Tk/deps/deps.jl that points to the system libTk. I changed this to point to the MacPorts libTk.8.8.6.dylib.
I noticed there is a Tk/deps/build.jl that calls an is_apple() function and calls TkMacOSXGetRootControl (which is not a function in the MacPorts libTk). I just commented out this call.

Conclusion:
After making the above changes, I could get julia to open the Tk widget on my remote machine; however, there are additional errors which can be traced to is_apple()-based conditionals in the Tkwidget.jl function. I was not quite bold enough experiment with changing these.

Request:
Can you modify Tk.jl so that it checks for the MacPorts libTk at build time and uses it if it finds it? It would be wonderful if the Tkwidget would open on my remote machine when connected to the OS X host, thus duplicating the behavior under linux.

All the best,
Ed

**Comment by aviks** [comment]
With #148, we do not use system version of Tk. We build our own. I think this fixes it.
