### ISSUE TITLE
There's no documentation

### ISSUE THREAD

**Issue by timothywalsh** [JuliaGraphics/Tk.jl#153]
There is no documentation over at [https://juliahub.com/docs/Tk/BVfq8/0.7.0/](https://juliahub.com/docs/Tk/BVfq8/0.7.0/ )

**Comment by aviks** [comment]
Yes, unfortunately there was some issues generating the docs. Looking into it. 

For the moment, please see

* https://github.com/JuliaGraphics/Tk.jl/blob/master/docs/src/index.md
and 
* https://github.com/JuliaGraphics/Tk.jl/tree/master/examples

**Comment by ViralBShah** [comment]
In fact the documentation just points to the documentation...

**Comment by LilithHafner** [comment]
https://lilithhafner.github.io/Tk.jl/dev
