### ISSUE TITLE
Tk.jl fails on Debian with recent builds of Julia

### ISSUE THREAD

**Issue by cmundi** [JuliaGraphics/Tk.jl#69]
Please see this issue: https://github.com/nolta/Winston.jl/issues/133 which I filed against Winston but which appears to belong here.

**Comment by afternone** [comment]
I edit `~/.julia/v0.5/Tk/deps/deps.jl` by changing the line
`
@checked_lib libtk "/home/hui/.julia/v0.5/Tk/deps/usr/lib/libtk8.6.so"
`
to
`
@checked_lib libtk "/usr/lib/libtk8.6.so"
`
and everything is ok now

**Comment by aviks** [comment]
All of this should go away with #148
