### ISSUE TITLE
Use library groups to separate 8.5 from 8.6

### ISSUE THREAD

**Issue by staticfloat** [JuliaGraphics/Tk.jl#80]
@Keno Here is yet another place where it'd be nice to setup two `library_group`s and force BinDeps to choose one or the other, but not both.  This isn't really segregating by provider, but rather segregating by package name.  The other being `VideoIO.jl`, where we have to choose between trying to install `ffmpeg` or `libav`.

**Comment by aviks** [comment]
Not relevant any more, with BinaryProvider
